name: Empty PR Description

on:
  pull_request:
    types: [ready_for_review]

jobs:
  empty-pr-description-comment:
    permissions:
      issues: write
    runs-on: ubuntu-latest
    steps:
      - run: |
          if [ "$BODY" == '' ] ; then
            gh pull_request comment "$NUMBER" --body "$MESSAGE"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.pull_request.number }}
          BODY: ${{ github.event.pull_request.body }}
          MESSAGE: >
            It looks like you didn't add a description to your pull request. Please edit and add as much detail as possible for the reviewers. Pull requests require a description before they will be reviewed - thank you.
